name: expense_wise
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.62.0
  sqflite: ^2.2.5
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_colorpicker: ^1.0.3

flutter:
  assets:
            - assets/img.png
  fonts:
    - family: Pacifico

  uses-material-design: true

